### ISSUE TITLE
Games popularity - asc / desc same response 

### ISSUE THREAD

**Issue by Titansfly** [igdb/api#1]
Doesn't matter if you put asc or desc always give back response as asc

**Comment by krazyjakee** [comment]
Please post the full request url for context.

**Comment by Titansfly** [comment]
import { Component, OnInit } from '@angular/core';
import {Http,Response,RequestOptions,Headers,HttpModule}from "@angular/http";

@Component({
  selector: 'app-topgames',
  templateUrl: './topgames.component.html',
  styleUrls: ['./topgames.component.css']
})
export class TopgamesComponent implements OnInit {

  apiRoot: string='https://igdbcom-internet-game-database-v1.p.mashape.com/games/?fields=name%2Cgenres%2Cscreenshots&limit=50&offset=0&order=popularity%3Adesc';

  topGames: [any];

  constructor(private http:Http) { }

  ngOnInit() {
    let url = `${this.apiRoot}/get`;
    let headers = new Headers;
    headers.append("X-Mashape-Key", "Ynp1iy0IK1mshfNydL2ZHEUHCUuNp1RPWoIjsngl7S0T6cXTHW");
    headers.append("Accept", "application/json");
    let options= new RequestOptions({ headers : headers});
    this.http.get(url,options).subscribe(
        res => {
          //console.log(res.json());
          this.topGames=res.json();
          console.log(this.topGames);
        }
    );
  }

}

**Comment by lephyrius** [comment]
Looks like u append `/get` on the request string here:
`let url = ${this.apiRoot}/get;`
Try without it:
`let url = this.apiRoot;`
