### ISSUE TITLE
Examples of [in], [not_in], and [any] filters

### ISSUE THREAD

**Issue by Stropaganda** [igdb/api#10]
I've been trying to use these filters to grab games only on select platforms, but it keeps returning empty results. An example would be nice.

**Comment by sharpless512** [comment]
Hi Stropaganda,

Thank you for using our API. Could you provide an example of the url/query you used?

Thanks

**Comment by Stropaganda** [comment]
Here is the url and params variable.

let url = "https://igdbcom-internet-game-database-v1.p.mashape.com/games/";
let params = {}
params['fields'] = '*';
params['filter[id][any]'] = [3,14,34,39,55,6,37,41,46,48,49,72,130];
params['limit'] = '50';

Here is the complete request.

https://igdbcom-internet-game-database-v1.p.mashape.com/games/?fields=*&filter%5Bid%5D%5Bany%5D=3&filter%5Bid%5D%5Bany%5D=14&filter%5Bid%5D%5Bany%5D=34&filter%5Bid%5D%5Bany%5D=39&filter%5Bid%5D%5Bany%5D=55&filter%5Bid%5D%5Bany%5D=6&filter%5Bid%5D%5Bany%5D=37&filter%5Bid%5D%5Bany%5D=41&filter%5Bid%5D%5Bany%5D=46&filter%5Bid%5D%5Bany%5D=48&filter%5Bid%5D%5Bany%5D=49&filter%5Bid%5D%5Bany%5D=72&filter%5Bid%5D%5Bany%5D=130&limit=50
I'm pretty sure I just don't know how to set the 'filter[id][any]' value
correctly. The docs say the value should be an comma separated array.

**Comment by krazyjakee** [comment]
@Stropaganda sorry for the late reply, I've been busy this weekend `/games/28414,26758?fields=*&order=release_dates.date:asc&limit=50` should work for you
You can see more example of this logic being used here: https://igdb.github.io/api/basics/examples/
