### ISSUE TITLE
Coming soon example, please.

### ISSUE THREAD

**Issue by mamiaro** [igdb/api#12]
Hi everyone, if i want to get the same information on coming soon page (https://www.igdb.com/games/coming_soon?pfilter=48) what filters needs to use on url api ?

**Comment by sharpless512** [comment]
Hi Mamiaro!

With the release_dates endpoint it should work.
`https://api-2445582011268.apicast.io/release_dates/?fields=*&filter[platform][eq]=48&order=date:asc&filter[date][gt]=1500619813000`

1500619813000 is then the timestamp of today in miliseconds

**Comment by mamiaro** [comment]
Ahhh thank you so much :D .. i been using /games/ endpoint.. so, i never get that results good.. thx !! :)

**Comment by sharpless512** [comment]
Glad I could help :)
