### ISSUE TITLE
Expander isn't working for developers and publishers in Game endpoint.

### ISSUE THREAD

**Issue by Dancovich** [igdb/api#14]
I'm trying to query games with their developers and publishers but the expander API isn't working to expand these fields.

Here are some of the things I tried:

* /games/?expand=developers,publishers&fields=id,name,developers.name,publishers.name
* /companies/?expand=published,developed&fields=id,name,published.id,published.name,developed.id,developed.name

All of these respond with `{"status":400,"message":"This model doesn't contain expandable field: XYZ"}`

The example on the Expander documentation work though.

**Comment by krazyjakee** [comment]
@Dancovich Sorry about this! We are aware and have an internal ticket and failing tests. We will have this issue and others resolved before the end of August. I'll leave this ticket open so you will be notified when the fix is deployed.

**Comment by Dancovich** [comment]
Thanks for the response. My app won't be ready by the end of August so I can wait for this feature to be fixed.

**Comment by krazyjakee** [comment]
Documentation has been updated
