### ISSUE TITLE
No efficient way to get a game's platforms

### ISSUE THREAD

**Issue by Szasza** [igdb/api#17]
Hi IGDB team,

I hope all is well.

During the testing of the expander feature I have tried to retrieve the platforms a game is available on. I started from the game and added the `release_dates` to it. This worked fine but I got stuck afterwards because the _Release date_ entity contains the _platform_ field as an integer, not as an expandable field.

Firing off as many extra requests as there are platforms seems somewhat inefficient. Would it be possible to consider switching out the integer value for an expandable field for `release_date.platform`?

Thank you in advance for your insights.

**Comment by jasonsokolowski** [comment]
Agreed. Immediately ran into this issue with my very first query. Out of all of the available expandable fields, this seems like it should be a first priority. Getting a list of all Battlefield games by platform is super inefficient.

**Comment by digitalh2o2** [comment]
I'm facing the same issue currently and do hope they'll come up with a solution instead of multiple calls to retrieve platforms.

**Comment by mitchhymel** [comment]
I ran into the same problem. The workaround I'm using is to make a request to the platforms endpoint, providing the id's of all the platforms I want. So you only need to make one extra request, assuming you can make a list of all platforms you want (but your scenario may not allow you to do this).

For example:
https://api-2445582011268.apicast.io/platforms/38,55,8,6,36,45,39?fields=*

**Comment by krazyjakee** [comment]
You can now expand a platforms field that appears at the root of the games endpoint: `/games/?fields=platforms.name&expand=platforms`
