### ISSUE TITLE
Filtering by release dates no longer working

### ISSUE THREAD

**Issue by dsmann12** [igdb/api#18]
Filtering by release dates worked before, but now I am getting errors. 

Here is an example of a failing request:

/games/?filter[release_dates.date][gt]=2005-12-31&limit=5&offset=0&order=release_dates.date:desc&search=zelda&fields=name,release_dates.date,rating,hypes,cover

However, other filters work fine, such as:

- /games/?filter[cover][exists]=true&limit=5&offset=0&order=release_dates.date:desc&search=zelda&fields=name,release_dates.date,rating,hypes,cover

This is only happening when trying to filter for release dates.

**Comment by sharpless512** [comment]
This should be fixed now
