### ISSUE TITLE
Endpoint "Game" doesn't support documented field: "weighted_rating"

### ISSUE THREAD

**Issue by Rayne** [igdb/api#19]
The endpoint `Game` returns the following error message when the *documented* field `weighted_rating` is added to the query:

```json
{"status":400,"message":"This model doesn't contain field: weighted_rating"}
```

**Example**

```bash
curl -X GET --header "Accept: application/json" --header "user-key: …" "https://…apicast.io/games/?fields=weighted_rating"
```

**Comment by Szasza** [comment]
@Rayne you are correct, albeit it is not a bug of the API. The documentation has not been updated when the `weighted_rating` field was removed/replaced. I would like to recommend that for the time being use the `/games/meta` endpoint to get all the available fields.

The documentation is being updated, the correct fields will be present for all endpoints within the next 2-3 days.
