### ISSUE TITLE
Filtering with postfix GT and GTE no return

### ISSUE THREAD

**Issue by fiott248** [igdb/api#24]
Hi i had a script working with using filtering ( filter[release_dates.date][gte] ) i have also tried to use the First_release_date field too. i have released the issue was coming when using the postfix GT and GTE i have tested on other postfix and they work like LT and LTE and EQ. can you please look in to i for now i will try to work around it by changing the method of filtering i guess thanks from advance.

**Comment by krazyjakee** [comment]
This was fixed
