### ISSUE TITLE
Option to return the whole info about games/genres/platforms/etc

### ISSUE THREAD

**Issue by erperejildo** [igdb/api#26]
I'm testing these endpoints: 

- https://api-2445582011268.apicast.io/games/

- /release_dates/?fields=*&filter[platform][eq]=48&order=date:asc&filter[date][gt]=1500619813000

What I get with each endpoint is a list with IDs but not the whole info about these games.
If I'd like to display a list of games I'd have to use one of these endpoints and do another call for each game.

Is this correct or maybe I'm forgetting some parameter here?

**Comment by krazyjakee** [comment]
This parameter: https://igdb.github.io/api/references/expander/

**Comment by erperejildo** [comment]
Lovely. Thank you so much @krazyjakee

**Comment by krazyjakee** [comment]
@erperejildo very welcome!
