### ISSUE TITLE
No navbar when confirming email address

### ISSUE THREAD

**Issue by aplocher** [igdb/api#29]
When I clicked the link to confirm my email address in my email, I was taken to the normal dashboard page (ish), only it was very confusing for a new user like myself because it states on the page:  

"Get started - Go to Live Test from navbar, select an endpoint. Provide the correct headers (use your key)"

The problem is, the navbar didn't exist until I re-entered that URL (after I was already activated).  It's really just a dead-end after I clicked the link from the email.

**Comment by krazyjakee** [comment]
Are you sure that a notification wasn't covering the navbar? I'm aware of that problem, there is a little X to the right which you can click to remove it.

You're totally right though, those notifications such. I will look into it today. Thanks so much for taking the time to report this.

**Comment by aplocher** [comment]
Oh you are right! Even just signing in it's there.  I had no idea that was a notification.  Might I suggest keeping this open issue just as a suggestion to improve that particular portion of your UX? :)

![image](https://user-images.githubusercontent.com/1132447/36299337-60b59920-12b1-11e8-90a5-60e61e2f11c7.png)

**Comment by krazyjakee** [comment]
@aplocher absolutely, I'll close this when that damn thing is gone. Again, thank you very much.
