### ISSUE TITLE
Broken Pagenation

### ISSUE THREAD

**Issue by OfficialGMYT** [igdb/api#3]
When on the https://igdb.github.io/api/basics/ page and you click to go to the page to the right the Endpoints URL is incorrect and outputs a 404. 

Incorrect URL: https://igdb.github.io/api//basics/endpoints
Correct URL: https://igdb.github.io/api/endpoints/

**Comment by Szasza** [comment]
The correct URL is https://igdb.github.io/api/basics/examples
