### ISSUE TITLE
DDoS Page on API Response

### ISSUE THREAD

**Issue by pbromwelljr** [igdb/api#42]
![igdb_ddos](https://user-images.githubusercontent.com/13454776/45928049-2f112b80-bf0b-11e8-9e33-327a987f9d15.PNG)
I'm getting this page when trying to access this endpoint on my server:

https://api-endpoint.igdb.com/games/?filter[name][prefix]=Spider-&filter[platforms][in]=48&fields=id,name

I've tried other filter criteria and I get the same response.

Can you help?

**Comment by krazyjakee** [comment]
Hi there, we are aware of the issue and are working to restore the service, thanks.
