### ISSUE TITLE
Change API management from market.mashape.com

### ISSUE THREAD

**Issue by AndyGee** [igdb/api#5]
The gateway market.mashape.com is rarely up or is impossibly slow to use. Please consider using an alternative.

**Comment by krazyjakee** [comment]
There has been discussion about hosting the API ourself but it means building a full monitoring/billing system and we just don't have the resources to commit to that at the moment as our focus is on the database itself. It's why we went with Mashape in the first place.

Let me know if you know of any alternatives as google & alternative.to are not turning up anything useful.

**Comment by Szasza** [comment]
@krazyjakee how about RapidAPI - https://rapidapi.com ?

**Comment by krazyjakee** [comment]
@Szasza It's weird because our Mashape support tickets are being responded to by RapidAPI staff, so I presume it's the same company but under a different name. I am checking it out though, the front-end certainly seems faster.

**Comment by Szasza** [comment]
I see. It's a shame, thank you for the investigation nonetheless @krazyjakee.

I have found another two potential candidates, one being [Apigee](https://apigee.com), the other is [IBM API Connect](https://www-03.ibm.com/software/products/en/api-connect).

The latter one's monetisation is still under development, will [come soon](https://developer.ibm.com/apiconnect/2017/03/17/coming-soon-api-monetization-capability-ibm-api-connect/).

I hope it helps, thank you again for looking into the matter.

**Comment by krazyjakee** [comment]
@Szasza We stopped looking into Apigee because of it's cost.

IBM API looks interesting, we can certainly look into that.

**Comment by Szasza** [comment]
@krazyjakee thank you for the further investigation, it is much appreciated.

@AndyGee so far your issue wasn't solved. I suggest using some kind of backend workers and proper filtering conditions to fetch the needed bits and pieces of data from IGDB and store it locally. I appreciate that this makes the application more complex but in exchange it will also be more durable since in a worst-case scenario of MashApe being down you can still operate your app and serve somewhat stale data.

**Comment by krazyjakee** [comment]
I finally managed to figure out IBM pricing and sadly, it's VERY expensive and we just cannot afford that at this time. I have my eye on RapidAPI. They haven't responded yet but I'm going to ask what their plans are.

**Comment by Szasza** [comment]
Sounds good, shame about the IBM pricing. Thank you again.

**Comment by krazyjakee** [comment]
@Szasza We are in contact with them at the moment. They are figuring out a proposal that might work for both of us. I'll let you know the conclusion.

**Comment by krazyjakee** [comment]
Mashape have merged with RapidAPI. RapidAPI are taking over and we are working with them to get things going. The data is currently being synchronised between rapidapi and mashape so your existing mashape credentials will work on rapidAPI. Lots more information here: http://blog.rapidapi.com/2017/05/23/rapidapi-and-mashape-api-marketplace-join-forces/

It's a happy day!
