### ISSUE TITLE
Inadequate examples

### ISSUE THREAD

**Issue by donfour** [igdb/api#50]
Hi, thank you for the great api!

I'm just started looking into the api, but I'm having trouble finding examples for even the most basic usages (e.g. finding games by name). For example, the doc for the [game](https://igdb.github.io/api/endpoints/game/) endpoint does not talk about how I can search / filter my results. Am I missing anything?

Thanks for any help in advance!

**Comment by Szasza** [comment]
Hi @donfour ,

You can find both in the Reference section.

Filtering: https://igdb.github.io/api/references/filters/
Ordering: https://igdb.github.io/api/references/ordering/

**Comment by donfour** [comment]
@Szasza opps didn't see it, my bad. Thanks for the quick reply!

**Comment by Szasza** [comment]
@donfour no worries, happy to help :+1:
