### ISSUE TITLE
Game logo

### ISSUE THREAD

**Issue by ridhwaans** [igdb/api#53]
I didnt find an endpoint for the game logo. The api docs show logos for the game company and the game engine. I am looking for the api to return the logo of the game itself, svg or any format.

**Comment by krazyjakee** [comment]
We don't have that data yet. You will need cover.

**Comment by ridhwaans** [comment]
Is that a priority, because it would be super useful once available

**Comment by krazyjakee** [comment]
We want this data, absolutely, but I know they won't be available any time soon, sorry.
