### ISSUE TITLE
X-Next-Page header not returned

### ISSUE THREAD

**Issue by TheRealBenForce** [igdb/api#58]
I'm using the following URL:
https://api-v3.igdb.com/platforms?fields=id,abbreviation,name&limit=50&order=name&scroll=1

I receive back a list of 50 platforms as well as the X-Count header, but X-Next-Page is missing.

**Comment by krazyjakee** [comment]
Scroll API has been deprecated. You can only use limit and offset now. See what else has changed here https://api-docs.igdb.com/#what-s-changed
