### ISSUE TITLE
Involed_companies can't be search

### ISSUE THREAD

**Issue by polo195pl** [igdb/api#60]
Hey i try search in involved_companies with query: 
https://api-v3.igdb.com/involved_companies/?fields=*&limit=50&search=Test
But return 500 error
![image](https://user-images.githubusercontent.com/22961693/59548393-06283f00-8f4f-11e9-848a-b0735d756576.png)

**Comment by Vendrad** [comment]
From the documentation you can see the only endpoints that are "Searchable" are... Characters - Collections - Games - People - Platforms - Themes. (https://api-docs.igdb.com/#search-176)

But thank you for letting us know, a more verbose message to the user would be appropriate in this case and cause less confusion.
